// Code generated by entc, DO NOT EDIT.

package recruitment

const (
	// Label holds the string label denoting the recruitment type in the database.
	Label = "recruitment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// Table holds the table name of the recruitment in the database.
	Table = "recruitments"
)

// Columns holds all SQL columns for recruitment fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
)
