// Code generated by entc, DO NOT EDIT.

package ent

import (
	"devroute/ent/developer"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Developer is the model entity for the Developer schema.
type Developer struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName string `json:"last_name,omitempty"`
	// FirstName holds the value of the "first_name" field.
	FirstName string `json:"first_name,omitempty"`
	// LastNameFurigana holds the value of the "last_name_furigana" field.
	LastNameFurigana string `json:"last_name_furigana,omitempty"`
	// FirstNameFurigana holds the value of the "first_name_furigana" field.
	FirstNameFurigana string `json:"first_name_furigana,omitempty"`
	// ProfileName holds the value of the "profile_name" field.
	ProfileName string `json:"profile_name,omitempty"`
	// IconURL holds the value of the "icon_url" field.
	IconURL string `json:"icon_url,omitempty"`
	// Gender holds the value of the "gender" field.
	Gender developer.Gender `json:"gender,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Developer) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case developer.FieldID:
			values[i] = new(sql.NullInt64)
		case developer.FieldLastName, developer.FieldFirstName, developer.FieldLastNameFurigana, developer.FieldFirstNameFurigana, developer.FieldProfileName, developer.FieldIconURL, developer.FieldGender:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Developer", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Developer fields.
func (d *Developer) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case developer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			d.ID = int(value.Int64)
		case developer.FieldLastName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[i])
			} else if value.Valid {
				d.LastName = value.String
			}
		case developer.FieldFirstName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field first_name", values[i])
			} else if value.Valid {
				d.FirstName = value.String
			}
		case developer.FieldLastNameFurigana:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name_furigana", values[i])
			} else if value.Valid {
				d.LastNameFurigana = value.String
			}
		case developer.FieldFirstNameFurigana:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field first_name_furigana", values[i])
			} else if value.Valid {
				d.FirstNameFurigana = value.String
			}
		case developer.FieldProfileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_name", values[i])
			} else if value.Valid {
				d.ProfileName = value.String
			}
		case developer.FieldIconURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon_url", values[i])
			} else if value.Valid {
				d.IconURL = value.String
			}
		case developer.FieldGender:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gender", values[i])
			} else if value.Valid {
				d.Gender = developer.Gender(value.String)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Developer.
// Note that you need to call Developer.Unwrap() before calling this method if this Developer
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Developer) Update() *DeveloperUpdateOne {
	return (&DeveloperClient{config: d.config}).UpdateOne(d)
}

// Unwrap unwraps the Developer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Developer) Unwrap() *Developer {
	tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Developer is not a transactional entity")
	}
	d.config.driver = tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Developer) String() string {
	var builder strings.Builder
	builder.WriteString("Developer(")
	builder.WriteString(fmt.Sprintf("id=%v", d.ID))
	builder.WriteString(", last_name=")
	builder.WriteString(d.LastName)
	builder.WriteString(", first_name=")
	builder.WriteString(d.FirstName)
	builder.WriteString(", last_name_furigana=")
	builder.WriteString(d.LastNameFurigana)
	builder.WriteString(", first_name_furigana=")
	builder.WriteString(d.FirstNameFurigana)
	builder.WriteString(", profile_name=")
	builder.WriteString(d.ProfileName)
	builder.WriteString(", icon_url=")
	builder.WriteString(d.IconURL)
	builder.WriteString(", gender=")
	builder.WriteString(fmt.Sprintf("%v", d.Gender))
	builder.WriteByte(')')
	return builder.String()
}

// Developers is a parsable slice of Developer.
type Developers []*Developer

func (d Developers) config(cfg config) {
	for _i := range d {
		d[_i].config = cfg
	}
}
