// Code generated by entc, DO NOT EDIT.

package ent

import (
	"devroute/ent/recruitment"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Recruitment is the model entity for the Recruitment schema.
type Recruitment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Recruitment) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case recruitment.FieldID:
			values[i] = new(sql.NullInt64)
		case recruitment.FieldTitle, recruitment.FieldContent:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Recruitment", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Recruitment fields.
func (r *Recruitment) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recruitment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = int(value.Int64)
		case recruitment.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				r.Title = value.String
			}
		case recruitment.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				r.Content = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Recruitment.
// Note that you need to call Recruitment.Unwrap() before calling this method if this Recruitment
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Recruitment) Update() *RecruitmentUpdateOne {
	return (&RecruitmentClient{config: r.config}).UpdateOne(r)
}

// Unwrap unwraps the Recruitment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Recruitment) Unwrap() *Recruitment {
	tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Recruitment is not a transactional entity")
	}
	r.config.driver = tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Recruitment) String() string {
	var builder strings.Builder
	builder.WriteString("Recruitment(")
	builder.WriteString(fmt.Sprintf("id=%v", r.ID))
	builder.WriteString(", title=")
	builder.WriteString(r.Title)
	builder.WriteString(", content=")
	builder.WriteString(r.Content)
	builder.WriteByte(')')
	return builder.String()
}

// Recruitments is a parsable slice of Recruitment.
type Recruitments []*Recruitment

func (r Recruitments) config(cfg config) {
	for _i := range r {
		r[_i].config = cfg
	}
}
