// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Achievement is the predicate function for achievement builders.
type Achievement func(*sql.Selector)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// CompanyUser is the predicate function for companyuser builders.
type CompanyUser func(*sql.Selector)

// Developer is the predicate function for developer builders.
type Developer func(*sql.Selector)

// Recruitment is the predicate function for recruitment builders.
type Recruitment func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
